### ISSUE TITLE
How to match data frames without overlapping features

### ISSUE THREAD

**Issue by RoseString** [shuxiaoc/mario-py#1]
Hello,

Thank you for the promising tool. I ran the following code with my 3 dataframes without overlapping features and failed. I also tried setting 'n_components_ovlp' to 0, but it didn't work. Do you know the parameters to run the pipeline in my case? Thank you!

```
final_matching_lst, embedding_lst = pipelined_mario(
    data_lst=[df1,df2,df3], normalization=True, n_batches=4,
    n_matched_per_cell=1, sparsity_ovlp=5, sparsity_all=500,
    n_components_ovlp=15, n_components_all=15,
    n_cancor=5, n_wts=4,
    n_clusters=10, n_components_filter=10, bad_prop=0.2, max_iter_filter=20,
    knn=False, embed_dim=10, max_iter_embed=500, save_path='.', verbose=False
)

```

> Matching data_lst[0] with data_lst[1]
> Now at batch 0
> Matching using overlapping features...
>  ** On entry to DGETRF parameter number  4 had an illegal value
> /Users/userX/opt/anaconda3/envs/mario/lib/python3.8/site-packages/mario/match.py:75: UserWarning: n_components exceed the number of overlapping features, set it to be the number of overlapping features.
>   warnings.warn("n_components exceed the number of overlapping features,"

**Comment by shuxiaoc** [comment]
Hi,

The current version of this package does not support matching with purely non-overlapping features. The algorithm implemented here requires at least one overlapping feature to get started. 

Perhaps [this paper](https://www.nature.com/articles/s41467-020-20249-2) and [this paper](https://academic.oup.com/bioinformatics/article/36/Supplement_2/i919/6055906?login=true) are closer to what you want?

**Comment by RoseString** [comment]
Thanks Shuxiao for pointing out the papers. In the end, I used mixOmics, which worked pretty well in my case.

**Comment by shuxiaoc** [comment]
Glad to hear that!
