### ISSUE TITLE
array must not contain infs or NaNs

### ISSUE THREAD

**Issue by nadavyayon** [shuxiaoc/mario-py#2]
Hi i'm getting this error while none of my arrays contain inf or Nans:
'array must not contain infs or NaNs'
i'm running this on jupyterHub :
  df1 = aData.to_df()
  df1.replace([np.inf, -np.inf, np.nan], 0 , inplace=True)
  df2 = bData
  df2.replace([np.inf, -np.inf, np.nan], 0 , inplace=True)
  final_matching_lst, embedding_lst = pipelined_mario(data_lst=[df1,df2])

full message:
Matching data_lst[0] with data_lst[1]
Now at batch 0
Matching using overlapping features...
/opt/conda/lib/python3.8/site-packages/sklearn/utils/extmath.py:152: RuntimeWarning: invalid value encountered in matmul
else:
ValueError Traceback (most recent call last)
in
----> 1 final_matching_lst, embedding_lst = pipelined_mario(data_lst=[df1,df2])

/opt/conda/lib/python3.8/site-packages/mario/match.py in pipelined_mario(data_lst, normalization, n_batches, n_matched_per_cell, sparsity_ovlp, sparsity_all, n_components_ovlp, n_components_all, n_cancor, n_wts, n_clusters, n_components_filter, bad_prop, max_iter_filter, knn, embed_dim, normalize_embed, max_iter_embed, save_path, verbose)
836 print('Matching using overlapping features...', flush=True)
837 mario.specify_matching_params(n_matched_per_cell)
--> 838 _ = mario.compute_dist_ovlp(n_components_ovlp)
839 _ = mario.match_cells('ovlp', sparsity=sparsity_ovlp)
840 print('Matching using all features...', flush=True)

/opt/conda/lib/python3.8/site-packages/mario/match.py in compute_dist_ovlp(self, n_components)
88
89 self.stacked_svd['U'], self.stacked_svd['s'], self.stacked_svd['Vh'] =
---> 90 randomized_svd(np.concatenate((arr1, arr2), axis=0), n_components=n_components)
91 if n_components == len(self.ovlp_features):
92 dist_mat = utils.cdist_correlation(arr1, arr2)

/opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
61 extra_args = len(args) - len(all_args)
62 if extra_args > 0:
---> 63 # ignore first 'self' argument for instance methods
64 args_msg = ['{}={}'.format(name, arg)
65 for name, arg in zip(kwonly_args[:extra_args],

/opt/conda/lib/python3.8/site-packages/sklearn/utils/extmath.py in randomized_svd(M, n_components, n_oversamples, n_iter, power_iteration_normalizer, transpose, flip_sign, random_state)
346 # this implementation is a bit faster with smaller shape[1]
347 M = M.T
--> 348
349 Q = randomized_range_finder(
350 M, size=n_random, n_iter=n_iter,

/opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
61 extra_args = len(args) - len(all_args)
62 if extra_args > 0:
---> 63 # ignore first 'self' argument for instance methods
64 args_msg = ['{}={}'.format(name, arg)
65 for name, arg in zip(kwonly_args[:extra_args],

/opt/conda/lib/python3.8/site-packages/sklearn/utils/extmath.py in randomized_range_finder(A, size, n_iter, power_iteration_normalizer, random_state)
231 Q = safe_sparse_dot(A, Q)
232 Q = safe_sparse_dot(A.T, Q)
--> 233 elif power_iteration_normalizer == 'LU':
234 Q, _ = linalg.lu(safe_sparse_dot(A, Q), permute_l=True)
235 Q, _ = linalg.lu(safe_sparse_dot(A.T, Q), permute_l=True)

/opt/conda/lib/python3.8/site-packages/scipy/linalg/decomp_lu.py in lu(a, permute_l, overwrite_a, check_finite)
207 """
208 if check_finite:
--> 209 a1 = asarray_chkfinite(a)
210 else:
211 a1 = asarray(a)

/opt/conda/lib/python3.8/site-packages/numpy/lib/function_base.py in asarray_chkfinite(a, dtype, order)
601 condlist = np.concatenate([condlist, condelse], axis=0)
602 n += 1
--> 603 elif n != n2:
604 raise ValueError(
605 "with {} condition(s), either {} or {} functions are expected"

ValueError: array must not contain infs or NaNs

Thanks!!

**Comment by ilan-gold** [comment]
I am running into a similar issue, perhaps, where I get `ValueError: Input contains NaN, infinity or a value too large for dtype('float64').`.  I have CITE-seq + Cytof data and I believe the RNA data is log-normalized:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_19266/2264757026.py in <module>
----> 1 final_matching_lst, embedding_lst = pipelined_mario(data_lst=[df_cite_cov.reset_index(drop=True), df_cytof_cov.reset_index(drop=True)])

~/software/miniconda3/envs/protein-env/lib/python3.8/site-packages/mario/match.py in pipelined_mario(data_lst, normalization, n_batches, n_matched_per_cell, sparsity_ovlp, sparsity_all, n_components_ovlp, n_components_all, n_cancor, n_wts, n_clusters, n_components_filter, bad_prop, max_iter_filter, knn, embed_dim, normalize_embed, max_iter_embed, save_path, verbose)
    839             _ = mario.match_cells('ovlp', sparsity=sparsity_ovlp)
    840             print('Matching using all features...', flush=True)
--> 841             _ = mario.compute_dist_all('ovlp', n_components_all)
    842             _ = mario.match_cells('all', sparsity=sparsity_all)
    843             print('Finding the best interpolated matching...', flush=True)

~/software/miniconda3/envs/protein-env/lib/python3.8/site-packages/mario/match.py in compute_dist_all(self, matching, n_components, max_iter)
    353             ):
    354                 # cached results are not valid, do CCA
--> 355                 cancor, cca = self.fit_cca(self.matching['ovlp'], n_components, max_iter)
    356                 self.ovlp_cancor = cancor
    357                 self.ovlp_scores['x'], self.ovlp_scores['y'] = cca.transform(self.df1, self.df2)

~/software/miniconda3/envs/protein-env/lib/python3.8/site-packages/mario/match.py in fit_cca(self, matching, n_components, max_iter)
    309         else:
    310             X, Y = self._align_modalities(matching)
--> 311         cancor, cca = embed.get_cancor(X, Y, n_components, max_iter)
    312 
    313         return cancor, cca

~/software/miniconda3/envs/protein-env/lib/python3.8/site-packages/mario/embed.py in get_cancor(X, Y, n_components, max_iter)
     29 
     30     cca = CCA(n_components=n_components, max_iter=max_iter)
---> 31     cca.fit(X, Y)
     32     X_c, Y_c = cca.transform(X, Y)
     33     cancor = np.corrcoef(

~/software/miniconda3/envs/protein-env/lib/python3.8/site-packages/sklearn/cross_decomposition/_pls.py in fit(self, X, Y)
    280         # copy since this will contains the residuals (deflated) matrices
    281         check_consistent_length(X, Y)
--> 282         X = self._validate_data(X, dtype=np.float64, copy=self.copy,
    283                                 ensure_min_samples=2)
    284         Y = check_array(Y, dtype=np.float64, copy=self.copy, ensure_2d=False)

~/software/miniconda3/envs/protein-env/lib/python3.8/site-packages/sklearn/base.py in _validate_data(self, X, y, reset, validate_separately, **check_params)
    418                     f"requires y to be passed, but the target y is None."
    419                 )
--> 420             X = check_array(X, **check_params)
    421             out = X
    422         else:

~/software/miniconda3/envs/protein-env/lib/python3.8/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

~/software/miniconda3/envs/protein-env/lib/python3.8/site-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    642 
    643         if force_all_finite:
--> 644             _assert_all_finite(array,
    645                                allow_nan=force_all_finite == 'allow-nan')
    646 

~/software/miniconda3/envs/protein-env/lib/python3.8/site-packages/sklearn/utils/validation.py in _assert_all_finite(X, allow_nan, msg_dtype)
     94                 not allow_nan and not np.isfinite(X).all()):
     95             type_err = 'infinity' if allow_nan else 'NaN, infinity'
---> 96             raise ValueError(
     97                     msg_err.format
     98                     (type_err,

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

I can try to share the data if this would help.  I also checked for nan, infinity and -ininfity in my data beforehand.

**Comment by shuxiaoc** [comment]
For nadavyayon the code failed when it was trying to do a SVD on the data. My current guess is that maybe some columns of your data are uniformly zero, so when you scale it by the standard deviation (which is controlled by the `normalization=True` argument in `pipelined_mario`) you get NaN.

For ilan-gold the code succeeded in the initial matching step (matching using shared/overlapping features) but the input to CCA had NaN/infinity. My guess is that the columns of your protein data all have non-zero standard deviations so the initial matching runs fine. But some columns of your RNA data have standard deviation zero and that caused the error when the code tried to incorporate those RNA features into account. Sharing the data will definitely help. Let us know what are the best ways to share the data --- we can be reached at `shuxiaoc@wharton.upenn.edu` and `bkzhu@stanford.edu`.

**Comment by ilan-gold** [comment]
Ok @shuxiaoc - I'll try to get something to you soon.  It will likely be a URL to a google drive or something, but if you have a different way of sharing you'd prefer let me know.  Just need better wifi to do the upload.  I was able to reproduce it even after running

```
sc.pp.filter_genes(adata_cite_cov, min_cells=10, inplace=True)
# Too many lowly expressed genes may be causing the mario pipeline to fail
sc.pp.highly_variable_genes(
    adata_cite_cov,
    n_top_genes=4000,
    flavor="seurat_v3",
    batch_key="COMBAT_participant_timepoint_ID",
    subset=True,
    layer="raw"
)
```
Perhaps it was not strong enough to filter genes but between the two calls, I'd think I would end up with some interesting features.

**Comment by shuxiaoc** [comment]
@ilan-gold Interesting I am not sure where things went wrong without taking a closer look at your data. Will wait for your url.

**Comment by ilan-gold** [comment]
@shuxiaoc I tried running it again when I got home and it worked.  I can provide you with the non-filtered data if that would help but running those scanpy commands seemed to help.

**Comment by shuxiaoc** [comment]
@ilan-gold  It's nice to hear the code works on your data. It makes me a bit more certain that the problem was caused by columns of the data whose standard deviations are zero. The filtering function from scanpy is one way to delete those columns.

@nadavyayon Please let us know if this solution works for you.

**Comment by nadavyayon** [comment]
Hi @shuxiaoc thanks for this prompt response. I didn't have a chance to try to run the code again with the suggested modifications. Will update as soon as I do. In the meantime I am happy that at least @ilan-gold had the issues fixed!

**Comment by nadavyayon** [comment]
If I see that this is dragging I will close the issue.
