### ISSUE TITLE
Questions about the joint embedding

### ISSUE THREAD

**Issue by XiHuYan** [shuxiaoc/mario-py#3]
Thanks for sharing this interesting work!

I have two questions:
1. It seems that Mario can only jointly embed those cells with high quality pairs. Is it possible for Mario to embed all cells (even for cells without pairs) into a latent space? For example, if setting `mario.specify_matching_params(5)`, I should be able to enable more cells pairing with others. However, is this such one-to-many matching appropriate for joint embedding?  e.g., the same cell will appear multiple times in the embedding space. 

2. In which scenario should I set `mario.specify_matching_params(2 or more)`? Could you provide a example?

**Comment by shuxiaoc** [comment]
For your first question, the current implementation of MARIO can only embeds high-quality pairs into a joint latent space. A manual work-around is to use those high-quality pairs to fit a CCA and then transform the whole datasets. We do have another tool called [MaxFuse](https://github.com/shuxiaoc/maxfuse), which is able to embed the whole datasets. 

For the second example, in many cases we just go with `specify_matching_params(1)`. If you do have strong prior knowledge that a cell in the first dataset will have 2 matches in the second, then setting `specify_matching_params(2)` may give better performance.

**Comment by XiHuYan** [comment]
Thanks, I'll try Maxfuse later.
