### ISSUE TITLE
Batching destroys injectivity of the final mapping

### ISSUE THREAD

**Issue by MeyerBender** [shuxiaoc/mario-py#4]
Hi,

first of all, thank you for creating this tool. When using MARIO on my own data, I came across a case where some cells in `df1` were mapped to the same cell in `df2`, meaning that the final mapping is not injective anymore. Is this expected behaviour, and if so, are there recommendations on how to deal with such cases?

Thank you very much!

**Comment by shuxiaoc** [comment]
Yes, batching indeed destroys injectivity of the final mapping.
If your computational resources permits, you could try run MARIO without batching (e.g., see [this](https://github.com/shuxiaoc/mario-py/blob/main/tutorials/mario-py-tutorial-BM.ipynb) tutorial) which will give you an injective map. Please be aware that running MARIO may take some time on large datasets.
We also have another (quite recently developed) tool called [MaxFuse](https://github.com/shuxiaoc/maxfuse) that scales better with large datasets if you feel like trying it out.
